version: '3.8'

services:
  db:
    image: mysql:8.0
    platform: linux/arm64
    container_name: humanerd-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Ulw/MkYZNYc7FOihWLLD5w==
      MYSQL_DATABASE: humanerd
      MYSQL_USER: humanerd
      MYSQL_PASSWORD: dEr/yG4klqLL4WhzwhG4Dg==
    volumes:
      - /Volumes/humanerd/docker/wordpress/db:/var/lib/mysql
    ports:
      - "3307:3306"

  wordpress:
    image: wordpress:6.7-php8.3-apache
    platform: linux/arm64
    container_name: humanerd-wp
    depends_on:
      - db
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: humanerd
      WORDPRESS_DB_PASSWORD: dEr/yG4klqLL4WhzwhG4Dg==
      WORDPRESS_DB_NAME: humanerd
      WORDPRESS_TABLE_PREFIX: hnr_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_AUTO_UPDATE_CORE', false);
        define('DISALLOW_FILE_EDIT', true);
    volumes:
      - /Volumes/humanerd/docker/wordpress/wp-content:/var/www/html/wp-content
      - /Users/drew/.drewgent/wordpress/wp-content/plugins:/var/www/html/wp-content/plugins
      - /Users/drew/.drewgent/wordpress/wp-content/themes:/var/www/html/wp-content/themes
    ports:
      - "8080:80"
